<?php

namespace ContainerOI1aD7x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIndexControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Engine\Controller\IndexController' shared autowired service.
     *
     * @return \App\Engine\Controller\IndexController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Engine/Controller/IndexController.php';

        $container->services['App\\Engine\\Controller\\IndexController'] = $instance = new \App\Engine\Controller\IndexController(\dirname(__DIR__, 3));

        $instance->setContainer(($container->privates['.service_locator.s8u3c1w'] ?? $container->load('get_ServiceLocator_S8u3c1wService'))->withContext('App\\Engine\\Controller\\IndexController', $container));

        return $instance;
    }
}
