<?php

namespace ContainerOI1aD7x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInstallExtensionAssetsService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Install\Command\InstallExtensionAssets' shared autowired service.
     *
     * @return \App\Install\Command\InstallExtensionAssets
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Install/Command/InstallExtensionAssets.php';

        $container->privates['App\\Install\\Command\\InstallExtensionAssets'] = $instance = new \App\Install\Command\InstallExtensionAssets(NULL, \dirname(__DIR__, 3));

        $instance->setName('scrm:extension-asset-install');

        return $instance;
    }
}
